import React from 'react';
import { motion } from 'framer-motion';
import { SectionHeading } from './SectionHeading';
import { ConfidenceBadge } from './ConfidenceBadge';
import { Info } from 'lucide-react';

export const ConfidenceSection: React.FC = () => {
  const levels = [
    {
      type: 'official' as const,
      title: 'Official Data',
      badgeColor: 'bg-[#2E6B4F]',
      sources: 'Ministry Census, Reserve Bank of India, District Gazetteers, SLBC Data',
      description: 'Hard verified metrics sourced directly from official government records, banking registries, and institutional census databases.',
      examples: ['Bank interest rates', 'Panchayat boundaries', 'Registered Mandi volumes', 'Scheme subsidies']
    },
    {
      type: 'local' as const,
      title: 'Confirmed Locally',
      badgeColor: 'bg-[#D98E2C]',
      sources: 'Field Surveyors, Mandi Agents, Panchayat Samiti, Local Suppliers',
      description: 'Empirical signals cross-validated directly with ground merchants, transport nodes, and local trade association telemetry.',
      examples: ['Local footfall density', 'Actual wholesale price ranges', 'Competitor inventory speed', 'Freight costs']
    },
    {
      type: 'estimated' as const,
      title: 'Estimated',
      badgeColor: 'bg-[#94A3B8]',
      sources: 'Algorithmic Stress Models, Machine Learning Projection Engine',
      description: 'Predictive estimates generated by financial stress simulations, demand elasticity formulas, and payback scenario modeling.',
      examples: ['Off-season revenue drop', 'Loan default risk margin', '5-year profit growth', 'Working capital depletion']
    }
  ];

  return (
    <section id="entrepreneurs" className="py-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto border-t border-[#E4E9F0]/10">
      
      <SectionHeading
        eyebrow="TRANSPARENT TRUST ARCHITECTURE"
        title="Know how confident the system is."
        subtitle="Every important number carries a confidence level so users can distinguish verified information from estimates."
        align="center"
      />

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-12">
        {levels.map((lvl, index) => (
          <motion.div
            key={lvl.title}
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: index * 0.15 }}
            className="rounded-3xl bg-[#1B2E4A] border border-[#E4E9F0]/15 p-8 flex flex-col justify-between hover:border-[#D98E2C]/40 transition-all shadow-lg"
          >
            <div>
              <div className="flex items-center justify-between mb-6">
                <ConfidenceBadge type={lvl.type} size="md" />
                <span className="text-xs font-mono-data text-[#94A3B8]">LEVEL 0{index + 1}</span>
              </div>

              <h3 className="font-display text-2xl font-bold text-[#F6F5F1] mb-2">
                {lvl.title}
              </h3>

              <p className="text-sm text-[#94A3B8] leading-relaxed mb-6">
                {lvl.description}
              </p>
            </div>

            <div className="pt-6 border-t border-[#E4E9F0]/10 space-y-3">
              <span className="text-xs font-mono-data uppercase text-[#D98E2C] block font-semibold">
                Sources & Telemetry:
              </span>
              <p className="text-xs text-[#E4E9F0]/80 font-mono-data">
                {lvl.sources}
              </p>

              <span className="text-[11px] font-mono-data uppercase text-[#94A3B8] block pt-2">
                Applied to:
              </span>
              <div className="flex flex-wrap gap-1.5">
                {lvl.examples.map(ex => (
                  <span key={ex} className="px-2.5 py-1 rounded-full text-[11px] font-mono-data bg-[#20242B]/80 text-[#E4E9F0] border border-[#E4E9F0]/10">
                    {ex}
                  </span>
                ))}
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Reassurance Banner */}
      <div className="mt-12 p-6 rounded-2xl bg-[#1B2E4A]/60 border border-[#2E6B4F]/40 flex flex-col sm:flex-row items-center justify-between gap-4 text-center sm:text-left">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-[#2E6B4F]/20 border border-[#2E6B4F] flex items-center justify-center text-[#2E6B4F] shrink-0">
            <Info className="w-5 h-5" />
          </div>
          <div>
            <h4 className="font-display text-base font-bold text-[#F6F5F1]">
              Zero Black-Box Assumptions
            </h4>
            <p className="text-xs text-[#94A3B8] mt-0.5">
              VyapaarIQ explicitly flags high-uncertainty factors before you present your business plan to a bank manager.
            </p>
          </div>
        </div>
      </div>

    </section>
  );
};
